name = "llm-prompt-builder"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production environment - master branch
[env.production]
routes = [
  { pattern = "prompt-builder.benjaminjames.xyz", custom_domain = true }
]

# Staging environment - staging branch
[env.staging]
routes = [
  { pattern = "staging.prompt-builder.benjaminjames.xyz", custom_domain = true }
]
